### ISSUE TITLE
Question: licensing

### ISSUE THREAD

**Issue by wolfbeast** [silnrsi/graphite#1]
I maintain a fork of Mozilla code, released under the MPL v2. This will include the Graphite 2 library. Since your main licensing is LGPL but you also permit licensing under the MPL (but no version is supplied), would you prefer I include a specific license block with the contents of COPYING in it in the browser, or would it be OK to publish as-is under the MPL v2 without a prominent notification in the licensing page?

**Comment by mhosken** [comment]
Dear Moonchild,

> I maintain a fork of Mozilla code, released under the MPL v2 This will include the Graphite 2 library Since your main licensing is LGPL but you also permit licensing under the MPL (but no version is supplied), would you prefer I include a specific license block with the contents of COPYING in it in the browser, or would it be OK to publish as-is under the MPL v2 without a prominent notification in the licensing page?

feel free to use MPL v2 or v1 (since no version specified). No prominent notification is required.

Yours,
Martin
\

**Comment by wolfbeast** [comment]
Great! Thank you, Martin :smile:
