### ISSUE TITLE
How can i use the Graphite in an android project

### ISSUE THREAD

**Issue by 1137889088** [silnrsi/graphite#10]
I want to use this technology in an android project to Mongolian display，but i don't now how to use it;

**Comment by mhosken** [comment]
There are two meanings of 'use' here. One is how to integrate graphite into an application where you have control over the position of glyphs, for example, rendering directly to a canvas.

I assume, though, that you are asking about the second interpretation where you have a graphite font and you want to use it in a webview type application. This is much harder. One solution is to use a patched version of crosswalk that adds Graphite support to a cross version webview.

We do have such a thing, so I would be interested in hearing how much interest there is in such a thing from users of Graphite.

**Comment by 1137889088** [comment]
We have made the character library. Integrate graphite into an application is first step ,to use it in a webview type application is also need.But first problem is how to invoke;The example you give show it can only  work for Android 2.2 - Android 2.3.1 ,How can i solve the ploblem。
![Uploading QQ截图20170310204403.png…]()

**Comment by 1137889088** [comment]
We want to intensive study the Graphite.
