### ISSUE TITLE
Compressed tables not working quite right

### ISSUE THREAD

**Issue by mhosken** [silnrsi/graphite#11]
There is a bug in the decompressor that can cause a font to be rejected if the right conditions exist when the table is compressed using lz4hc. There is a work around (compress up to the last 4 bytes then tack the last 4 bytes onto the final copy), But the engine should be fixed to not have this problem.

**Comment by bobh0303** [comment]
It should be noted that the above-mentioned workaround is not incompatible with fixing the engine -- font developers can deploy the workaround today (at a very slight loss in compression) and fonts would remain compatible with any future engine fix.

To that end, the [pysilfont](https://github.com/silnrsi/pysilfont) utility currently known as [FTgrCompress](https://github.com/silnrsi/pysilfont/blob/master/lib/silfont/scripts/FTgrCompress.py) implements this compression workaround.

**Comment by tim-eves** [comment]
Fixed in latest release 3.11
