### ISSUE TITLE
Awami Nastaliq font collision issue

### ISSUE THREAD

**Issue by wolfbeast** [silnrsi/graphite#13]
On the demo page (http://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_fontdemo) I noticed that the Awami Nastaliq font renders almost correctly in 1.3.10 in Mozilla-based browser code, but it seems one contraction isn't done.

The browser renders:
![image2](https://user-images.githubusercontent.com/3359132/27347086-88ff7c22-55ef-11e7-954f-e7f986c060d8.png)

And the graphical example shows:
![image3](https://user-images.githubusercontent.com/3359132/27347100-96990646-55ef-11e7-96fe-06a160237fea.png)

**Comment by mhosken** [comment]
Renders fine for me on firefox 55. Can you recheck.

**Comment by wolfbeast** [comment]
Seems to be OK in ESR52 (and you tested 55), however it seems 57 nightly doesn't do this kind of collision at all anymore.
I'll have a look into what might be the cause in our own browser which uses the same lib. Possibly it's a problem at a higher level with space contextuals not being honored properly (that would cause this, right?)

**Comment by wolfbeast** [comment]
I found the problem -- seems it's a Mozilla implementation bug you've participated in, actually ;)
The problem being word caching being applied when cross-space contextuals are supported, splitting up the characters because of the space. Easy fix; not a bug in graphite, per se, so closing this issue.
