### ISSUE TITLE
fnttxtrender doesn't work with python3

### ISSUE THREAD

**Issue by reneengelhard** [silnrsi/graphite#16]
Hi,

in Debian we (temporarily) lost the python2 module for fonttools (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876439).

As said there, this resulted in graphite2s testsuite failing miserably, since it of course can't find its

from fontTools.ttLib import TTFont

import anymore. See
https://buildd.debian.org/status/logs.php?pkg=graphite2&ver=1.3.10-3&suite=sid.

(Now the python2 module is back, but let's ignore this for this issues sake.)

So we needed to migrate it to python3. I started with it and Mattia thankfully completed it.

See
https://anonscm.debian.org/cgit/pkg-openoffice/graphite2.git/tree/debian/patches/testsuite-python3.diff. With that patch it builds with python3 (but probably will not work with python2...)

Do you want/need to keep python2 compat? Or could this just applied as-is and requring python3?

Regards,

Rene

**Comment by tim-eves** [comment]
Hi Rene,

I've just pushed d96d572627cde920af9044e0b6386e2edf56e767 and 3ab48d1e2ba14c3369f7b8649a49fec601382bc4 which enables fnttxtrender and associated modules to work with python3 and 2.7.

**Comment by mapreri** [comment]
@tim-eves 
Thank you!

But whilst that's definitely going to make it, I wonder if it would be possible to also have "something" done to Graphite.cmake so that either one of python or python3 is called when running the tests.  Currently 'python' is hardcoded in the test commands.

**Comment by tim-eves** [comment]
@mapreri 

I've removed the use of "hardcoded' python invocations in https://github.com/silnrsi/graphite/commit/20df932dcf24be7a38b64f295cf158a1194e9bf3.
The hardcoding assumed in the absence of `python2` being installed that `python3` would become the default `python` and everything would keep working.

**Comment by mapreri** [comment]
At least in Debian, there are currently no plans on making /usr/bin/python point to python3 at any point in the future.  We (which includes me) are quite sure a lot would break with such move, despite that PEP talking about changing the default.

So, thank you for un-hardcoding the pythhon executable name :)

And regarding the shebang change, I believe that wouldn't really help much (that would only help for people having the python executable in a different path, like /usr/local/bin, etc).  but given that the tests are not executed directly it doesn't really matter.
