### ISSUE TITLE
Add grapite project to CI service

### ISSUE THREAD

**Issue by tysmith** [silnrsi/graphite#20]
Adding graphite to a CI can help prevent regression and is fairly easy to setup. It can automatically perform different builds and runs unit tests on each commit.

There are many good free options available:
- https://travis-ci.org/
- https://ci.appveyor.com

**Comment by mhosken** [comment]
We are already doing CI Building (as we have since 2011) and we do therefore catch regressions. In the case of mingw, we don't officially support that and I doubt any of these services would provide a mingw based build out of the box.

**Comment by tysmith** [comment]
That's great! I see @tim-eves just added the badges.

In the case of mingw setting it up on TravisCI (the system I know best) should be trivial. You just apt-get what is needed in setup and list the compilers and commands to run.

Another reason I brought this up is because my build broke when the mingw fix went in. My build script looks basically like this (run from a subdir):
```
cmake -G "Unix Makefiles" -DCMAKE_SKIP_RPATH:BOOL=YES -DGRAPHITE2_NTRACING:BOOL=YES -DCMAKE_CXX_COMPILER:FILEPATH=clang++ -DCMAKE_C_COMPILER:FILEPATH=clang -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_SHARED_LIBS:BOOL=OFF  -DCMAKE_CXX_FLAGS="-frtti" -DCMAKE_EXE_LINKER_FLAGS:STRING="-lstdc++" ..
make -j8
```
