### ISSUE TITLE
pkg-config --modversion graphite2 returns bogus version

### ISSUE THREAD

**Issue by jbeich** [silnrsi/graphite#3]
Trying to check graphite2 version via pkg-config returns ABI? version rather than project version. This makes it impossible to require a version with a particular vulnerability fixed without having to compile-check against GR2_VERSION_\* macros.

``` sh
$ pkg info -x graphite
graphite2-1.3.8

$ pkg-config --modversion graphite2
3.0.1
```

**Comment by mhosken** [comment]
the pkg-config number reflects the library version number not the package version number. This is in a different format to package version numbers. Thus 3.0.1 represents that the api is version 3.0 with an age of 1 meaning it supports version 2 apis as well. There is never any intention that the two should be the same. If pkg-config were to support both, then that would be great.

If you have suggestions on how to support both version numbers in a helpful way, I'm open to considering it.

**Comment by mhosken** [comment]
No action required
