### ISSUE TITLE
Some problems for Graphite-enabled fonts list

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [silnrsi/graphite#31]
I have found some problems when I read your [Graphite-enabled fonts](scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_fonts) list.
1. UnifrakturMaguntia has its own home page at [SourceForge](http://unifraktur.sourceforge.net/), but what you link to is Google Code and it was thrown into Google Code Archive.
2. I have noticed you created new Graphite font Awami Nastaliq, but you haven't seen it in this list.

**Comment by sharoncorrell** [comment]
Fixed.
