### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frenzymadness** [silnrsi/graphite#36]
Hello.

Would it be possible to create a new release, please? Some Linux distributions started to switch to Python 3 only environment and commits in the master branch contain some fixes and improvements regarding Python 3 compatibility.

Thank you and have a nice day.
Lumír

**Comment by bgermann** [comment]
Please see also #37.

**Comment by mirabilos** [comment]
Please do include #40 in the next release, too. Thanks!

**Comment by bgermann** [comment]
I guess you got a new release now. However Python 3 compatibility for the test and fuzzing is not there yet. Please include #38 to fix this.

**Comment by tim-eves** [comment]
All of the above PRs have either been merged or closed and the build system is now requiring Python 3.6 or greater for test and tool scripts (exception being the graphite2.py module, which 2 & 3 compatible).
