### ISSUE TITLE
Making more features woks with Graphite2

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [silnrsi/graphite#4]
The [Graphite technical overview](http://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_techAbout#8d40d897) has said:

> Graphite2 represents a significant (10x) optimization in terms of speed and greatly improved robustness, but does not include a few features such a ligature component handling and cross-line-boundary contextualization.

Despite Graphite2 engine got some breakthroughs in its history, some features does not supported by Graphite2 would affect the advantages of Graphite2, also cause some inconveniences for developers whose want to convert from SilGraphite to Graphite2. To make better quality text layout, Graphite2 should get solution for them.

**Comment by sharoncorrell** [comment]
Do you know of a specific, real-life need for cross-line-boundary
    contextualization or being able to select and highlight ligature
    components individually? These were not implemented in Graphite2
    because it was not clear that they are needed. The ligature
    complement mechanism in particular, while it makes for a nice demo,
    is not something that affects real-life usability.
    
    On 8/4/2016 1:17 PM, Krasnaya Ploshchad
      wrote:
    
    
      The Graphite
          technical overview has said:
      
        Graphite2 represents a significant (10x) optimization in
          terms of speed and greatly improved robustness, but does not
          include a few features such a ligature component handling and
          cross-line-boundary contextualization.
      
      Despite Graphite2 engine got some brakethroughs in its history,
        some features does not supported by Graphite2 would affect
        advantages of Graphite2, also cause some unconveniences for
        developers whose want to convert from SilGraphite to Graphite2.
        To make better quality text layout, Graphite2 should get
        solution for them.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/silnrsi/graphite","title":"silnrsi/graphite","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/silnrsi/graphite"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Making more fetures woks with Graphite2 (#4)"}],"action":{"name":"View Issue","url":"https://github.com/silnrsi/graphite/issues/4"}}}

**Comment by KrasnayaPloshchad** [comment]
I have found that [Linux Libertine G](http://numbertext.org/linux/) have implemented ligature features as both OpenType and Graphite feature.

**Comment by sharoncorrell** [comment]
Ligatures work fine in Graphite2. They work just like they do in
    OpenType.
    
    What was not implemented in Graphite2 was a rather fancy mechanism
    for selecting and editing ligature components. For instance, suppose
    you have a ligature displayed as ấ -
    lowercase as with circumflex and acute - with three underlying
    characters in the data. The more sophisticated mechanism in
    SilGraphite would allow you to drag over the circumflex and visually
    highlight just it. Then you could hit Delete and just the circumflex
    is deleted, leaving just á. That fancy
    selection and highlighting mechanism was not put in Graphite2. It is
    nice but did not seem really necessary for any script we were aware
    of.
    
    
    On 8/7/2016 7:10 AM, Krasnaya Ploshchad
      wrote:
    
    
      I have found that Linux Libertine G have
        implemented ligature features as both OpenType and Graphite
        feature.
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/silnrsi/graphite","title":"silnrsi/graphite","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/silnrsi/graphite"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KrasnayaPloshchad in #4: I have found that [Linux Libertine G](http://numbertext.org/linux/) have implemented ligature features as both OpenType and Graphite feature."}],"action":{"name":"View Issue","url":"https://github.com/silnrsi/graphite/issues/4#issuecomment-238078943"}}}

**Comment by mhosken** [comment]
No action required.
