### ISSUE TITLE
arm-linux-g++: error: unrecognized command line option '-msse2'

### ISSUE THREAD

**Issue by sapone** [silnrsi/graphite#43]
```
if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86|i.86")
        add_definitions(-mfpmath=sse -msse2)
```
This is really bad for cross-compilation. Target system should be checked, not the host one.

**Comment by tim-eves** [comment]
It would be really bad if CMake we're designed to automatically detect cross-compiling.  This is in fact correct and to do what you need requires you to create a toolchain file, which would allow you to set the CMAKE_SYSTEM_PROCESSOR to arm.  More details are here https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html#id6
