### ISSUE TITLE
never use md5 and/or sha1 for the file hashes

### ISSUE THREAD

**Issue by requiredregistration** [silnrsi/graphite#47]
use sha512

**Comment by tim-eves** [comment]
Some context here would help, are you referring to the SHAs for release doc? I cannot find any mention of md5 in our source repo so I'm uncertain what you might be referring to there.

**Comment by tim-eves** [comment]
I have updated our release document to use sha256sum in commit a661ed68a569a572a02e28f0060067bbe063660f. In the absence of any other uses of sha1 or md5 in our code base I am closing this issue.
