### ISSUE TITLE
Support italic feature

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [silnrsi/graphite#48]
Does Graphite having this support? If so any fonts would be allowed to add italic variant even if the fonts having single face.

**Comment by KrasnayaPloshchad** [comment]
Since OpenType is already have this feature, it would be nice if Graphite can provide attributes to achieve the equalance, also, with this support any webfonts would be lighter.

**Comment by mhosken** [comment]
Graphite isn't OpenType and OpenType isn't Graphite. If you want OpenType support, use OpenType. If you want the flexibility of Graphite, use Graphite. But Graphite, while it gives you the power to control everything yourself, also gives you the responsibility. Graphite knows nothing of GSUB or GPOS tables and never will.
