### ISSUE TITLE
awamicmp{1,2,3} fail

### ISSUE THREAD

**Issue by reneengelhard** [silnrsi/graphite#49]
Hi,

graphite 1.3.13 fails its tests for me. 1.3.12 works fine. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918685 and https://buildd.debian.org/status/package.php?p=graphite2&suite=experimental:

```
75/92 Test #75: awamicmp1 ........................***Failed    1.01 sec
43.1 Failed
57.1 Failed
160.1 Failed
162.1 Failed

      Start 76: awamicmp2
76/92 Test #76: awamicmp2 ........................***Failed    1.00 sec
43.1 Failed
57.1 Failed
160.1 Failed
162.1 Failed

      Start 77: awamicmp3
77/92 Test #77: awamicmp3 ........................***Failed    0.97 sec
160.1 Failed
161.1 Failed
162.1 Failed
```

(on a clean amd64 chroot, too)

I saw that 49fce465ae4ee921f81e9fb8270177c16849a3e9 updated the values. Reverting that commit makes the test pass for me...

The weird thing is that it builds fine in my "working" sid chroot with all kinds of other packages installed. Is that check expecting something present not checked for? Or some specific version? 
But that also then would make the other font tests fail?

Any hint welcome..

Regards,

Rene

**Comment by mhosken** [comment]
Hmm. Could this be a compiler difference? Any difference in the compilers used on the two systems? Any differences in build parameters? A build log of the failing tests would help. Can't find any in the build logs you link to (but it may be hiding :)).

**Comment by reneengelhard** [comment]
Hmm, indeed, they vanished by now since I uploaded this to unstable.

You might be right, the test fails on testing (https://ci.debian.net/data/autopkgtest/testing/amd64/g/graphite2/1682895/log.gz, that test does https://salsa.debian.org/libreoffice-team/graphite2/blob/master/debian/tests/test; that autopkgtests are supposed to test the installed packages so the hacks to remove references to just-built stuff where possible) whereas it works in unstable.... When that test is ran in unstable I'll post here...

But I can also diff build logs... (and diff the .jsons)

**Comment by reneengelhard** [comment]
(That is the package which has the patch, so it probably would work in testing as is in your version, and works in unstable only when reverting 49fce465ae4ee921f81e9fb8270177c16849a3e9)

**Comment by reneengelhard** [comment]
So it means that whatever broke seems to be fixed now. https://buildd.debian.org/status/package.php?p=graphite2&suite=sid is with my hack reverted and stock upstream tests. So it succeeds now....

**Comment by tim-eves** [comment]
Based on @reneengelhard last comments this appears to be fixed now, so I'm closing this issue.  Please re-open if there is still a problem.
