### ISSUE TITLE
Let Graphite font variable

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [silnrsi/graphite#6]
Several months ago, OpenType introduced Font Variation technology, but it cannot be recognized by Graphite engine, to fix it, introducing Graphite based font variation would be useful.

**Comment by sharoncorrell** [comment]
That's an interesting idea, but it would be a substantial development effort, which at this point in time I really don't foresee us investing in.

**Comment by KrasnayaPloshchad** [comment]
It would be awesome if Graphite Font Variation is implemented, it would give some conveniences to process or adjust text alignment within multiple scripts layout, also intergrate different weights within single font file.

**Comment by mhosken** [comment]
@KrasnayaPloschad, do you have a font that you have created with Graphite tables in that you want to add font variation to? If so, I would love to see it.

**Comment by KrasnayaPloshchad** [comment]
Well, I have discussed with Aleksandr Andreev. In [this issue](https://github.com/typiconman/fonts-cu/issues/3) he thought OpenType Variation can be used to implement expanding widths of Titlo, but is still low priority. So I think Graphite can make some implementations to get the advantages of OT Font Variations.

**Comment by KrasnayaPloshchad** [comment]
[CSS Fonts Level 4](https://drafts.csswg.org/css-fonts-4/) introduced some attributes related to OpenType Font Variation, I’m puzzled there will be a conflict if a font intergrated both OT Variation and Graphite layouts used on the web.

**Comment by KrasnayaPloshchad** [comment]
AAT also has font variation.

**Comment by mhosken** [comment]
There are no plans to add this feature at the moment.

**Comment by KrasnayaPloshchad** [comment]
That's sad.
