### ISSUE TITLE
Better integration with HarfBuzz font functions

### ISSUE THREAD

**Issue by khaledhosny** [silnrsi/graphite#62]
HarfBuzz provides font function callbacks and allows clients to provides them (it provides also an internal implementation and a FreeType-based one). Currently libgraphite2 always accesses the font tables itself directly, breaking HarfBuzz-client code that depends on custom font functions (see https://github.com/harfbuzz/harfbuzz/issues/1822).

Lingraphite should provide away to override its internal font functions, allowing for a tighter integration with HarfBuzz. It would be also nice for reducing size of static builds (e.g. WASM builds).

**Comment by mhosken** [comment]
I'm unsure what lingraphite is. I will assume it's a regular mistyping of libgraphite. In terms of future integrations, we would expect graphite to do all font interaction through the harfbuzz font layer. It is true that at the moment, the graphite integration parses font tables directly (although supplied by harfbuzz, when integrated), but as we tighten the integration, I would expect only the graphite tables to be so parsed.
