### ISSUE TITLE
Cmake versions and deprecation warnings

### ISSUE THREAD

**Issue by n7s** [silnrsi/graphite#71]
building with cmake 3.22.1 (to target jammy in our next toolchain), I just noticed a few deprecation warnings:

CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.

Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.

Focal (current version of our toolchain) is at 3.16.3.

**Comment by tim-eves** [comment]
Fixed in f9dad5a35edb0c3f1031f5627623fb9e7f9bc24c
