### ISSUE TITLE
Access denied when opening the docs

### ISSUE THREAD

**Issue by KOLANICH** [silnrsi/graphite#81]
>Access denied
>Error code 1020
>You do not have access to scripts.sil.org.
>The site owner may have set restrictions that prevent you from accessing the site.

when opening https://scripts.sil.org/cms/scripts/render_download.php?site_id=projects&format=file&media_id=GDLdocumentation&filename=GDLdocumentation.pdf (the link is from https://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_devFont , which opens)

(with both using "Russian" and "non-Russian" (but a "datacenter" one) IP address)

**Comment by LornaSIL** [comment]
We're having a bit of a problem with downloads on scripts.sil.org right now. We're trying to address it, but it might be next week before it's resolved.

**Comment by tim-eves** [comment]
I've investigated and found the issue to be caused by our CDN providers Web Application Firewall and forwarded the details onto our domain admins for the sil.org. domain.

**Comment by tim-eves** [comment]
Worked with our domain admins to fix the blocking, and this link is now accessible again.
